M48
; DRILL file {KiCad (6.0.9)} date Sun Nov 20 11:02:23 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-20T11:02:23-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X0.9055Y-0.9055
X0.9055Y-2.5984
X4.0157Y-0.9055
X4.0157Y-2.5984
T0
M30
